runtime: python27
api_version: 1
threadsafe: true

handlers:
  # Favicon icon and other...
  - url: /(.*\.(ico|gif|png|jpeg|jpg|css|js|svg))$
    static_files: angular/\1
    upload: angular/(.*)
    expiration: "10d"
  # Images in assets folder
  - url: /assets/images/(.*\.(png|jpeg|jpg|svg))$
    static_files: angular/assets/images/\1
    upload: angular/assets/images/(.*)
    expiration: "365d"
  # Fonts in assets folder
  - url: /assets/fonts/(.*\.(eot|woff|woff2|svg))$
    static_files: angular/assets/fonts/\1
    upload: angular/assets/fonts/(.*)
    expiration: "365d"
  # Everything else
  - url: /.*
    static_files: angular/index.html
    upload: angular/index.html
